#!/usr/bin/env bash
set -euo pipefail

grep -q "$1" meson.build || (echo "Couldn't find version $1 in meson.build" && exit 1)
sed -i "s/$1/$2/g" meson.build
git add meson.build
git commit -m "version $2"
exit 0